<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fmpxml="http://www.filemaker.com/fmpxmlresult" version="1.0">
	<!--
				An XSLT Template to import an XML file #name# into #a FileMaker database#.
				Please adjust this template as necessary.
				
				This file was generated by MrWatson's automatic FileMaker Import XSLT generator 'FMPXMLRESULT_XSLT_CreateXMLImportTemplate.xsl'
		
		
		
		FMSaveAsXML_FMPXMLRESULT_ImportFileUUID.xsl
			-->
	<!-- ===== HEAD ===== -->
	<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes" omit-xml-declaration="no" cdata-section-elements="Calculation Text Data"/>
	<!-- ===== VARIABLES ===== -->
	<xsl:variable name="foundcount">
		<xsl:value-of select="0"/>
	</xsl:variable>
	<!-- ===== TEMPLATES ===== -->
	<!-- Main -->
	<xsl:template match="/">
		<FMPXMLRESULT xmlns="http://www.filemaker.com/fmpxmlresult">
			<ERRORCODE>0</ERRORCODE>
			<PRODUCT BUILD="03-07-2021" NAME="FileMaker" VERSION="Pro 19.2.2"/>
			<DATABASE DATEFORMAT="D.m.yyyy" LAYOUT="" NAME="adv-WebSync-Datenmodell.fmp12" RECORDS="311" TIMEFORMAT="k:mm:ss "/>
			<METADATA>
				<FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="FileName" TYPE="TEXT"/>
				<FIELD EMPTYOK="YES" MAXREPEAT="1" NAME="FileUUID" TYPE="TEXT"/>
			</METADATA>
			<RESULTSET FOUND="{$foundcount}">
				<xsl:apply-templates select="*"/>
			</RESULTSET>
		</FMPXMLRESULT>
	</xsl:template>
	<!-- ROW -->
	<xsl:template match="/FMSaveAsXML">
		<xsl:variable name="filebasename">
			<xsl:value-of select="substring-before(@File, '.')"/>
		</xsl:variable>
		<ROW>
			<!-- Column 1: FileName (TEXT)-->
			<COL>
				<DATA>
					<xsl:value-of select="$filebasename"/>
				</DATA>
			</COL>
			<!-- Column 2: FileUUID (TEXT)-->
			<COL>
				<DATA>
					<xsl:value-of select="@UUID"/>
				</DATA>
			</COL>
		</ROW>
	</xsl:template>
	<!-- ignore all other text -->
	<xsl:template match="text()"/>
</xsl:stylesheet>
